spring.data.mongodb.uri=mongodb+srv://sebastianjuan514_db_user:Josemanuel16%2A@ac-ugm4o2i.rsaxu70.mongodb.net/vehiculos?appName=ac-ugm4o2i
server.port=8080
logging.level.org.mongodb.driver=WARN
spring.data.mongodb.read-preference=secondaryPreferred